import SwiftUI

// MARK: - Terms text

private let termsText = """
AQUIP — TERMS AND CONDITIONS

Last Updated: June 4, 2026

PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING THE AQUIP APPLICATION.

1. ACCEPTANCE OF TERMS

By using the Aquip application ("App"), you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. If you do not agree, do not use the App.

2. DISCLAIMER — NO WARRANTY OR LIABILITY

The App is provided strictly for informational and guidance purposes only. Aquip and its developers make no representations or warranties regarding the accuracy, completeness, or reliability of any water chemistry analysis, test results, or treatment recommendations generated by the App.

THE APP MAY CONTAIN BUGS, ERRORS, OR FAULTY ALGORITHMS THAT PRODUCE INCORRECT CALCULATIONS OR RECOMMENDATIONS. Neither Aquip nor its developers shall be held responsible or liable for any damages, injuries, harm to persons, property, or equipment, or any other adverse outcomes that may result from reliance on the App's analysis or guidance.

3. CHEMICAL HANDLING RESPONSIBILITY

The App may suggest the use of pool and spa chemicals. You assume full and sole responsibility for the safe purchase, handling, storage, mixing, and application of any chemicals. Aquip and its developers are not responsible for the misuse, improper handling, or any adverse effects resulting from the use of recommended products. Always follow manufacturer instructions, local regulations, and applicable safety guidelines when handling pool or spa chemicals.

4. USER RESPONSIBILITY

You, the user, are solely responsible for:

• Reviewing and independently verifying all results and recommendations before taking action.
• Ensuring the accuracy of all test strip readings entered into the App.
• Monitoring your pool or spa water chemistry independently and regularly.
• Exercising safe chemical practices at all times.
• Possessing, or obtaining, adequate pool/spa and chemical knowledge to ensure safety and to identify when App output may be incorrect.

5. NOT A SUBSTITUTE FOR PROFESSIONAL ADVICE

The App is designed to help guide users and should never be used as the sole or definitive source of information for water chemistry decisions. It is strongly recommended that you consult a qualified pool or spa professional for critical decisions. The App is not perfect, and you should not 100% rely on it.

6. LIMITATION OF LIABILITY

To the fullest extent permitted by applicable law, Aquip and its developers disclaim all liability for any direct, indirect, incidental, consequential, special, or punitive damages arising out of or in any way connected with the use of the App, regardless of the cause of action.

7. CHANGES TO TERMS

We reserve the right to modify these Terms and Conditions at any time. Continued use of the App following any changes constitutes your acceptance of the revised terms.

8. GOVERNING LAW

These Terms shall be governed by and construed in accordance with applicable law.

9. CONTACT

If you have any questions about these Terms and Conditions, please contact us through the App Store listing.
"""

// MARK: - First-launch / forced agreement popup

struct TermsAgreementPopup: View {
    var onAgree: () -> Void

    @State private var isAgreed = false

    private let gradient = LinearGradient(
        colors: [
            Color(red: 37/255, green: 99/255, blue: 235/255),
            Color(red: 6/255, green: 182/255, blue: 212/255)
        ],
        startPoint: .leading,
        endPoint: .trailing
    )

    var body: some View {
        ZStack {
            Color.black.opacity(0.55).ignoresSafeArea()

            VStack(spacing: 0) {
                // Icon
                ZStack {
                    Circle()
                        .fill(Color(red: 219/255, green: 234/255, blue: 254/255))
                        .frame(width: 64, height: 64)
                    Image(systemName: "doc.text.fill")
                        .font(.system(size: 28))
                        .foregroundStyle(Color(red: 37/255, green: 99/255, blue: 235/255))
                }
                .padding(.top, 28)
                .padding(.bottom, 12)

                Text("Terms & Conditions")
                    .font(.system(size: 20, weight: .bold))
                    .foregroundStyle(Color(red: 17/255, green: 24/255, blue: 39/255))

                Text("Please read and agree before continuing")
                    .font(.system(size: 13))
                    .foregroundStyle(Color(red: 107/255, green: 114/255, blue: 128/255))
                    .padding(.top, 4)
                    .padding(.bottom, 14)

                // Scrollable T&C text
                ScrollView {
                    Text(termsText)
                        .font(.system(size: 11.5))
                        .foregroundStyle(Color(red: 55/255, green: 65/255, blue: 81/255))
                        .lineSpacing(2.5)
                        .padding(14)
                }
                .frame(height: 200)
                .background(Color(red: 249/255, green: 250/255, blue: 251/255))
                .overlay(
                    RoundedRectangle(cornerRadius: 12)
                        .stroke(Color(red: 229/255, green: 231/255, blue: 235/255), lineWidth: 1)
                )
                .clipShape(RoundedRectangle(cornerRadius: 12))
                .padding(.horizontal, 20)

                // Checkbox
                Button {
                    withAnimation(.easeInOut(duration: 0.15)) { isAgreed.toggle() }
                } label: {
                    HStack(alignment: .top, spacing: 12) {
                        ZStack {
                            RoundedRectangle(cornerRadius: 6)
                                .stroke(
                                    isAgreed
                                        ? Color(red: 37/255, green: 99/255, blue: 235/255)
                                        : Color(red: 209/255, green: 213/255, blue: 219/255),
                                    lineWidth: 2
                                )
                                .frame(width: 22, height: 22)
                            if isAgreed {
                                RoundedRectangle(cornerRadius: 4)
                                    .fill(Color(red: 37/255, green: 99/255, blue: 235/255))
                                    .frame(width: 22, height: 22)
                                Image(systemName: "checkmark")
                                    .font(.system(size: 12, weight: .bold))
                                    .foregroundStyle(.white)
                            }
                        }
                        .padding(.top, 1)
                        Text("I have read and agree to the Terms and Conditions")
                            .font(.system(size: 13))
                            .foregroundStyle(Color(red: 55/255, green: 65/255, blue: 81/255))
                            .multilineTextAlignment(.leading)
                            .fixedSize(horizontal: false, vertical: true)
                        Spacer()
                    }
                }
                .buttonStyle(.plain)
                .padding(.horizontal, 20)
                .padding(.top, 16)
                .padding(.bottom, 20)

                Divider()

                // Continue button
                Button(action: { if isAgreed { onAgree() } }) {
                    Text("Continue")
                        .font(.system(size: 16, weight: .semibold))
                        .foregroundStyle(
                            isAgreed
                                ? Color(red: 37/255, green: 99/255, blue: 235/255)
                                : Color(red: 156/255, green: 163/255, blue: 175/255)
                        )
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 16)
                }
                .disabled(!isAgreed)
                .buttonStyle(.plain)
            }
            .background(Color.white)
            .clipShape(RoundedRectangle(cornerRadius: 20))
            .shadow(color: .black.opacity(0.18), radius: 24, x: 0, y: 8)
            .padding(.horizontal, 28)
        }
    }
}

// MARK: - Full-page Terms & Conditions view (used in Settings)

struct TermsAndConditionsView: View {
    @Environment(AppSettings.self) private var settings
    @Environment(\.dismiss) private var dismiss

    var onBack: () -> Void

    @State private var showUncheckWarning = false

    private let gradient = LinearGradient(
        colors: [
            Color(red: 37/255, green: 99/255, blue: 235/255),
            Color(red: 6/255, green: 182/255, blue: 212/255)
        ],
        startPoint: .leading,
        endPoint: .trailing
    )

    var body: some View {
        ZStack {
            VStack(spacing: 0) {
                // Header
                VStack(alignment: .leading, spacing: 0) {
                    HStack {
                        Button(action: onBack) {
                            HStack(spacing: 6) {
                                Image(systemName: "chevron.left")
                                    .font(.system(size: 14, weight: .semibold))
                                Text("Back")
                                    .font(.system(size: 15))
                            }
                            .foregroundStyle(.white.opacity(0.9))
                        }
                        .buttonStyle(.plain)
                        Spacer()
                    }
                    .padding(.bottom, 14)

                    Text("Terms & Conditions")
                        .font(.system(size: 26, weight: .bold))
                        .foregroundStyle(.white)
                    Text("Review and manage your agreement")
                        .font(.system(size: 15))
                        .foregroundStyle(Color(red: 219/255, green: 234/255, blue: 254/255))
                        .padding(.top, 4)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.horizontal, 24)
                .padding(.top, 72)
                .padding(.bottom, 28)
                .background(gradient)

                // Content
                ScrollView {
                    VStack(alignment: .leading, spacing: 20) {
                        // T&C text card
                        VStack(alignment: .leading, spacing: 0) {
                            Text(termsText)
                                .font(.system(size: 13))
                                .foregroundStyle(Color(red: 55/255, green: 65/255, blue: 81/255))
                                .lineSpacing(3)
                                .padding(16)
                        }
                        .background(Color.white)
                        .clipShape(RoundedRectangle(cornerRadius: 14))
                        .shadow(color: .black.opacity(0.05), radius: 6, x: 0, y: 2)

                        // Agreement checkboxes
                        VStack(spacing: 0) {
                            checkboxRow(
                                label: "I have read the Terms and Conditions",
                                subtitle: "I have thoroughly read and understood the terms above."
                            )
                            Divider().padding(.leading, 56)
                            checkboxRow(
                                label: "I agree to the Terms and Conditions",
                                subtitle: "I accept all conditions, limitations, and responsibilities described."
                            )
                        }
                        .background(Color.white)
                        .clipShape(RoundedRectangle(cornerRadius: 14))
                        .shadow(color: .black.opacity(0.05), radius: 6, x: 0, y: 2)
                    }
                    .padding(20)
                    .padding(.bottom, 100)
                }
                .background(Color(red: 249/255, green: 250/255, blue: 251/255))
            }

            if showUncheckWarning {
                uncheckWarningPopup
                    .zIndex(10)
                    .transition(.opacity.combined(with: .scale(scale: 0.92)))
            }
        }
        .animation(.easeOut(duration: 0.2), value: showUncheckWarning)
    }

    @ViewBuilder
    private func checkboxRow(label: String, subtitle: String) -> some View {
        Button {
            if settings.hasAgreedToTerms {
                // User is trying to uncheck — show warning
                withAnimation(.easeOut(duration: 0.2)) { showUncheckWarning = true }
            } else {
                settings.hasAgreedToTerms = true
                settings.save()
            }
        } label: {
            HStack(alignment: .top, spacing: 14) {
                ZStack {
                    RoundedRectangle(cornerRadius: 6)
                        .stroke(
                            settings.hasAgreedToTerms
                                ? Color(red: 37/255, green: 99/255, blue: 235/255)
                                : Color(red: 209/255, green: 213/255, blue: 219/255),
                            lineWidth: 2
                        )
                        .frame(width: 22, height: 22)
                    if settings.hasAgreedToTerms {
                        RoundedRectangle(cornerRadius: 4)
                            .fill(Color(red: 37/255, green: 99/255, blue: 235/255))
                            .frame(width: 22, height: 22)
                        Image(systemName: "checkmark")
                            .font(.system(size: 12, weight: .bold))
                            .foregroundStyle(.white)
                    }
                }
                .padding(.top, 2)

                VStack(alignment: .leading, spacing: 3) {
                    Text(label)
                        .font(.system(size: 15, weight: .semibold))
                        .foregroundStyle(Color(red: 17/255, green: 24/255, blue: 39/255))
                    Text(subtitle)
                        .font(.system(size: 12))
                        .foregroundStyle(Color(red: 107/255, green: 114/255, blue: 128/255))
                        .lineSpacing(2)
                }
                Spacer()
            }
            .padding(16)
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
    }

    // MARK: - Uncheck warning popup

    private var uncheckWarningPopup: some View {
        ZStack {
            Color.black.opacity(0.5).ignoresSafeArea()

            VStack(spacing: 0) {
                ZStack {
                    Circle()
                        .fill(Color(red: 254/255, green: 243/255, blue: 199/255))
                        .frame(width: 64, height: 64)
                    Image(systemName: "exclamationmark.triangle.fill")
                        .font(.system(size: 28))
                        .foregroundStyle(Color(red: 217/255, green: 119/255, blue: 6/255))
                }
                .padding(.top, 28)
                .padding(.bottom, 16)

                Text("Cannot Continue Without Agreement")
                    .font(.system(size: 18, weight: .bold))
                    .foregroundStyle(Color(red: 17/255, green: 24/255, blue: 39/255))
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 20)
                    .padding(.bottom, 10)

                Text("You cannot use Aquip without agreeing to the Terms and Conditions. If you uncheck, you will be required to agree again before using the app.")
                    .font(.system(size: 14))
                    .foregroundStyle(Color(red: 107/255, green: 114/255, blue: 128/255))
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 24)
                    .padding(.bottom, 24)

                Divider()

                HStack(spacing: 0) {
                    Button {
                        withAnimation(.easeIn(duration: 0.18)) { showUncheckWarning = false }
                    } label: {
                        Text("Keep Agreement")
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundStyle(Color(red: 37/255, green: 99/255, blue: 235/255))
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 16)
                    }
                    .buttonStyle(.plain)

                    Divider().frame(height: 52)

                    Button {
                        withAnimation(.easeIn(duration: 0.18)) { showUncheckWarning = false }
                        settings.hasAgreedToTerms = false
                        settings.save()
                        // ContentView's .onChange will trigger the T&C popup
                    } label: {
                        Text("Uncheck")
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundStyle(Color(red: 220/255, green: 38/255, blue: 38/255))
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 16)
                    }
                    .buttonStyle(.plain)
                }
            }
            .background(Color.white)
            .clipShape(RoundedRectangle(cornerRadius: 20))
            .shadow(color: .black.opacity(0.18), radius: 24, x: 0, y: 8)
            .padding(.horizontal, 40)
        }
    }
}
